### ISSUE TITLE
Evaluate a new model

### ISSUE THREAD

**Issue by scampion** [JoelNiklaus/LEXTREME#6]
Hi 👋 , 
I want to test another model that I trained EUBERT  https://huggingface.co/EuropeanParliament/EUBERT

Did you plan to release a short documentation for that use case ?

**Comment by JoelNiklaus** [comment]
Hi,

Cool model! It is using the standard huggingface BERT architecture, right? 
We already have support for hierarchical models of the BERT architecture. 

@kapllan may be able to provide more documentation.

**Comment by scampion** [comment]
Indeed, it's based on RoBERTa and compliant with the huggingface 🤗 transformer framework in theory. 

Thanks, I look forward to evaluating it

**Comment by kapllan** [comment]
Hi @scampion,

sorry for the late response. I update the README. Here, you can find instructions how to add new models to the benchmark: https://github.com/JoelNiklaus/LEXTREME#add-a-new-model.

Also, make a new pull request from the main branch.

Please, let me know if there are any other issues.
